CREATE DATABASE ParkedVehicles;
GO
CREATE TABLE ParkedVehicles (
    VehicleID INT IDENTITY(1,1) PRIMARY KEY,
    VehicleNumber NVARCHAR(50),
    SlotID INT FOREIGN KEY REFERENCES ParkingSlots(SlotID),
    EntryTime DATETIME DEFAULT GETDATE(),
    ExitTime DATETIME NULL,
    Amount DECIMAL(10,2) NULL
);
GO